ServerEvents.recipes(event => {

  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:9}'), ['toughasnails:empty_gold_canteen', Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:8}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:7}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:6}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:5}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:4}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:3}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:2}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:1}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:0}'), [Item.of('toughasnails:gold_dirty_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:24}'), ['toughasnails:empty_netherite_canteen', Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:23}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:24}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:22}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:23}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:21}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:22}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:20}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:21}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:19}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:20}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:18}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:19}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:17}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:18}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:16}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:17}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:15}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:16}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:14}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:15}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:13}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:14}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:12}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:13}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:11}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:12}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:10}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:11}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:9}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:10}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:8}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:7}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:6}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:5}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:4}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:3}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:2}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:1}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:0}'), [Item.of('toughasnails:netherite_dirty_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])

    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:14}'), ['toughasnails:empty_diamond_canteen', Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:13}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:14}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:12}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:13}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:11}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:12}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:10}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:11}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:9}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:10}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:8}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:7}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:6}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:5}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:4}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:3}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:2}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:1}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:0}'), [Item.of('toughasnails:diamond_dirty_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])

  event.recipes.create.filling(Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:4}'), ['toughasnails:empty_leather_canteen', Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:3}'), [Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:2}'), [Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:1}'), [Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])
  event.recipes.create.filling(Item.of('toughasnails:leather_dirty_water_canteen'), [Item.of('toughasnails:leather_dirty_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:dirty_water', 250)])

  })

  ServerEvents.recipes(event => {

    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:9}'), ['toughasnails:empty_gold_canteen', Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:8}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:7}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:6}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:5}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:4}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:3}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:2}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:1}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_purified_water_canteen', '{Damage:0}'), [Item.of('toughasnails:gold_purified_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])

    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:24}'), ['toughasnails:empty_netherite_canteen', Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:23}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:24}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:22}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:23}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:21}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:22}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:20}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:21}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:19}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:20}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:18}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:19}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:17}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:18}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:16}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:17}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:15}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:16}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:14}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:15}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:13}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:14}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:12}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:13}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:11}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:12}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:10}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:11}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:9}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:10}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:8}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:7}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:6}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:5}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:4}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:3}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:2}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:1}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:0}'), [Item.of('toughasnails:netherite_purified_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])

    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:14}'), ['toughasnails:empty_diamond_canteen', Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:13}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:14}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:12}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:13}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:11}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:12}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:10}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:11}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:9}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:10}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:8}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:7}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:6}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:5}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:4}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:3}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:2}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:1}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:0}'), [Item.of('toughasnails:diamond_purified_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])

    event.recipes.create.filling(Item.of('toughasnails:leather_purified_water_canteen', '{Damage:4}'), ['toughasnails:empty_leather_canteen', Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_purified_water_canteen', '{Damage:3}'), [Item.of('toughasnails:leather_purified_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_purified_water_canteen', '{Damage:2}'), [Item.of('toughasnails:leather_purified_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_purified_water_canteen', '{Damage:1}'), [Item.of('toughasnails:leather_purified_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_purified_water_canteen'), [Item.of('toughasnails:leather_purified_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('toughasnails:purified_water', 250)])

    })

  ServerEvents.recipes(event => {

    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:9}'), ['toughasnails:empty_gold_canteen', Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:8}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:7}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:6}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:5}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:4}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:3}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:2}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:1}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:gold_water_canteen', '{Damage:0}'), [Item.of('toughasnails:gold_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('minecraft:water', 250)])

    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:24}'), ['toughasnails:empty_netherite_canteen', Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:23}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:24}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:22}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:23}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:21}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:22}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:20}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:21}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:19}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:20}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:18}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:19}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:17}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:18}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:16}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:17}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:15}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:16}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:14}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:15}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:13}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:14}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:12}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:13}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:11}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:12}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:10}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:11}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:9}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:10}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:8}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:7}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:6}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:5}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:4}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:3}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:2}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:1}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:netherite_water_canteen', '{Damage:0}'), [Item.of('toughasnails:netherite_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('minecraft:water', 250)])

      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:14}'), ['toughasnails:empty_diamond_canteen', Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:13}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:14}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:12}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:13}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:11}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:12}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:10}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:11}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:9}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:10}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:8}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:9}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:7}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:8}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:6}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:7}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:5}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:6}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:4}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:5}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:3}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:2}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:1}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('minecraft:water', 250)])
      event.recipes.create.filling(Item.of('toughasnails:diamond_water_canteen', '{Damage:0}'), [Item.of('toughasnails:diamond_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('minecraft:water', 250)])

    event.recipes.create.filling(Item.of('toughasnails:leather_water_canteen', '{Damage:4}'), ['toughasnails:empty_leather_canteen', Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_water_canteen', '{Damage:3}'), [Item.of('toughasnails:leather_water_canteen', '{Damage:4}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_water_canteen', '{Damage:2}'), [Item.of('toughasnails:leather_water_canteen', '{Damage:3}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_water_canteen', '{Damage:1}'), [Item.of('toughasnails:leather_water_canteen', '{Damage:2}').strongNBT(), Fluid.of('minecraft:water', 250)])
    event.recipes.create.filling(Item.of('toughasnails:leather_water_canteen'), [Item.of('toughasnails:leather_water_canteen', '{Damage:1}').strongNBT(), Fluid.of('minecraft:water', 250)])

    })
