ServerEvents.recipes(event => {
    event.remove({ input: 'quark:golden_carrot_crate' })
    event.remove({ output:'quark:golden_carrot_crate' })
    event.remove({ input: 'quark:beetroot_crate' })
    event.remove({ output:'quark:beetroot_crate' })
    event.remove({ input: 'quark:carrot_crate' })
		event.remove({ output:'quark:carrot_crate' })
    event.remove({ input: 'quark:cocoa_beans_sack' })
    event.remove({ output:'quark:cocoa_beans_sack' })
		event.remove({ input: 'quark:potato_crate' })
		event.remove({ output:'quark:potato_crate' })
    event.remove({ output:'vinery:dark_cherry_chair' })
    event.remove({ input: 'quark:apple_crate' })
		event.remove({ output:'quark:apple_crate' })
		event.remove({ input: 'quark:golden_apple_crate' })
		event.remove({ output:'quark:golden_apple_crate' })
		event.remove({ input: 'quark:glowberry_sack' })
		event.remove({ output:'quark:glowberry_sack' })
		event.remove({ input: 'quark:berry_sack' })
		event.remove({ output:'quark:berry_sack' })
		event.remove({ input: 'quark:gunpowder_sack' })
		event.remove({ output:'quark:gunpowder_sack' })
		event.remove({ input: 'quark:nether_wart_sack' })
		event.remove({ output:'quark:nether_wart_sack' })
		event.remove({ input: 'farmersdelight:carrot_crate' })
		event.remove({ output:'farmersdelight:carrot_crate' })
		event.remove({ input: 'farmersdelight:potato_crate' })
		event.remove({ output:'farmersdelight:potato_crate' })
		event.remove({ input: 'farmersdelight:beetroot_crate' })
		event.remove({ output:'farmersdelight:beetroot_crate' })
		event.remove({ input: 'farmersdelight:cabbage_crate' })
		event.remove({ output:'farmersdelight:cabbage_crate' })
		event.remove({ input: 'farmersdelight:tomato_crate' })
		event.remove({ output:'farmersdelight:tomato_crate' })
		event.remove({ input: 'farmersdelight:onion_crate' })
		event.remove({ output:'farmersdelight:onion_crate' })
    event.remove({ input: 'farmersdelight:onion_crate' })
    event.remove({ output:'farmersdelight:onion_crate' })
    event.remove({ input: 'quarkdelight:ancient_fruit_crate' })
    event.remove({ output:'quarkdelight:ancient_fruit_crate' })
    event.remove({ input: 'oreganized:lead_bolt_crate' })
    event.remove({ output:'oreganized:lead_bolt_crate' })

    event.remove({ input: 'nethervinery:crimson_grape_crate' })
    event.remove({ output:'nethervinery:warped_grape_crate' })
    event.remove({ input: 'nethervinery:warped_grape_crate' })
    event.remove({ output:'nethervinery:crimson_grape_crate' })
});




ServerEvents.recipes(event => {
	event.recipes.create.compacting('farmersdelight:cabbage_crate', ['spelunkers_charm:crate', '8x farmersdelight:cabbage'])
	event.recipes.create.compacting('farmersdelight:tomato_crate', ['spelunkers_charm:crate', '8x farmersdelight:tomato'])
	event.recipes.create.compacting('farmersdelight:onion_crate', ['spelunkers_charm:crate', '8x farmersdelight:onion'])
  event.recipes.create.compacting('quarkdelight:ancient_fruit_crate', ['spelunkers_charm:crate', '8x quark:ancient_fruit'])
  event.recipes.create.compacting('oreganized:lead_bolt_crate', ['spelunkers_charm:crate', '8x oreganized:lead_bolt'])
	event.recipes.create.compacting(['suppsquared:sack_orange', '8x minecraft:glow_berries'], 'quark:glowberry_sack')
	event.recipes.create.compacting(['suppsquared:sack_brown', '8x minecraft:sweet_berries'], 'quark:berry_sack')
	event.recipes.create.compacting(['suppsquared:sack_black','8x minecraft:gunpowder'], 'quark:gunpowder_sack')
	event.recipes.create.compacting(['suppsquared:sack_red','8x minecraft:nether_wart'], 'quark:nether_wart_sack')
  event.recipes.create.mixing('nethervinery:crimson_grape_crate',['supplementaries:sack','8x nethervinery:crimson_grape'])
  event.recipes.create.mixing('nethervinery:warped_grape_crate',['supplementaries:sack','8x nethervinery:warped_grape'])
  event.recipes.create.compacting(['supplementaries:sack','8x nethervinery:warped_grape'], 'nethervinery:warped_grape_crate')
  event.recipes.create.mixing('nethervinery:crimson_grape',['supplementaries:sack', '8x nethervinery:crimson_grape'])
  event.recipes.create.compacting(['supplementaries:sack','8x nethervinery:crimson_grape'], 'nethervinery:crimson_grape_crate')
  event.recipes.create.compacting('quark:golden_carrot_crate', ['spelunkers_charm:crate', '8x minecraft:golden_carrot'])
  event.recipes.create.mixing(['spelunkers_charm:crate', '8x minecraft:golden_carrot'],'quark:golden_carrot_crate')
  event.recipes.create.mixing(['spelunkers_charm:crate', '8x minecraft:beetroot'], 'quark:beetroot_crate')
  event.recipes.create.mixing(['spelunkers_charm:crate','8x farmersdelight:cabbage'],'farmersdelight:cabbage_crate')
  event.recipes.create.mixing(['spelunkers_charm:crate','8x farmersdelight:tomato'], 'farmersdelight:tomato_crate')
  event.recipes.create.mixing(['spelunkers_charm:crate','8x farmersdelight:onion'], 'farmersdelight:onion_crate')
  event.recipes.create.mixing(['spelunkers_charm:crate','8x quark:ancient_fruit'], 'quarkdelight:ancient_fruit_crate')
  event.recipes.create.mixing(['spelunkers_charm:crate','8x oreganized:lead_bolt'], 'oreganized:lead_bolt_crate')
	event.recipes.create.mixing(['spelunkers_charm:crate','8x minecraft:carrot'], 'quark:carrot_crate')
	event.recipes.create.mixing(['spelunkers_charm:crate','8x minecraft:potato'], 'quark:potato_crate')
	event.recipes.create.mixing(['spelunkers_charm:crate','8x minecraft:apple'], 'quark:apple_crate')
	event.recipes.create.mixing(['spelunkers_charm:crate','8x minecraft:golden_apple'], 'quark:golden_apple_crate')
	event.recipes.create.mixing('quark:glowberry_sack', ['suppsquared:sack_orange','8x minecraft:glow_berries'])
  event.recipes.create.mixing('quark:berry_sack', ['suppsquared:sack_red','8x minecraft:sweet_berries'])
	event.recipes.create.mixing('quark:gunpowder_sack', ['suppsquared:sack_black','8x minecraft:gunpowder'])
	event.recipes.create.mixing('quark:nether_wart_sack',['suppsquared:sack_red','8x minecraft:nether_wart'])
  event.recipes.create.mixing('quark:cocoa_beans_sack', ['suppsquared:sack_brown','8x minecraft:cocoa_beans'])
  event.recipes.create.compacting(['suppsquared:sack_brown','8x minecraft:cocoa_beans'],'quark:cocoa_beans_sack')
	event.recipes.create.compacting('quark:beetroot_crate', ['spelunkers_charm:crate','8x minecraft:beetroot'])
	event.recipes.create.compacting('quark:carrot_crate', ['spelunkers_charm:crate','8x minecraft:carrot'])
	event.recipes.create.compacting('quark:potato_crate', ['spelunkers_charm:crate','8x minecraft:potato'])
	event.recipes.create.compacting('quark:apple_crate', ['spelunkers_charm:crate','8x minecraft:apple'])
	event.recipes.create.compacting('quark:golden_apple_crate', ['spelunkers_charm:crate','8x minecraft:golden_apple'])
})
