
ServerEvents.recipes(event => {
  const resonarium =
    ['dagger',
      'parrying_dagger',
      'longsword',
      'katana',
      'saber',
      'rapier',
      'greatsword',
      'battle_hammer',
      'warhammer',
      'spear',
      'halberd',
      'pike',
      'lance',
      'longbow',
      'heavy_crossbow',
      'throwing_knife',
      'tomahawk',
      'javelin',
      'boomerang',
      'battleaxe',
      'flanged_mace',
      'glaive',
      'quarterstaff',
      'scythe']

  for (let upgrade of resonarium) {
    event.smithing(
      `spartandeeperdarker:resonarium_${upgrade}`,
      'deeperdarker:resonarium_upgrade_smithing_template',
      `spartanweaponry:iron_${upgrade}`,
      'deeperdarker:resonarium_plate'
    )
  }
}
)


ServerEvents.tags('item', event => {
  event.add('forge:weapons', ['spartandeeperdarker:resonarium_dagger',
    'spartandeeperdarker:resonarium_parrying_dagger',
    'spartandeeperdarker:resonarium_longsword',
    'spartandeeperdarker:resonarium_katana',
    'spartandeeperdarker:resonarium_saber',
    'spartandeeperdarker:resonarium_rapier',
    'spartandeeperdarker:resonarium_greatsword',
    'spartandeeperdarker:resonarium_battle_hammer',
    'spartandeeperdarker:resonarium_warhammer',
    'spartandeeperdarker:resonarium_spear',
    'spartandeeperdarker:resonarium_halberd',
    'spartandeeperdarker:resonarium_pike',
    'spartandeeperdarker:resonarium_lance',
    'spartandeeperdarker:resonarium_longbow',
    'spartandeeperdarker:resonarium_heavy_crossbow',
    'spartandeeperdarker:resonarium_throwing_knife',
    'spartandeeperdarker:resonarium_tomahawk',
    'spartandeeperdarker:resonarium_javelin',
    'spartandeeperdarker:resonarium_boomerang',
    'spartandeeperdarker:resonarium_battleaxe',
    'spartandeeperdarker:resonarium_flanged_mace',
    'spartandeeperdarker:resonarium_glaive',
    'spartandeeperdarker:resonarium_quarterstaff',
    'spartandeeperdarker:resonarium_scythe'])

  event.add('spartandeeperdarker:resonarium_weapons', ['spartandeeperdarker:resonarium_dagger',
    'spartandeeperdarker:resonarium_parrying_dagger',
    'spartandeeperdarker:resonarium_longsword',
    'spartandeeperdarker:resonarium_katana',
    'spartandeeperdarker:resonarium_saber',
    'spartandeeperdarker:resonarium_rapier',
    'spartandeeperdarker:resonarium_greatsword',
    'spartandeeperdarker:resonarium_battle_hammer',
    'spartandeeperdarker:resonarium_warhammer',
    'spartandeeperdarker:resonarium_spear',
    'spartandeeperdarker:resonarium_halberd',
    'spartandeeperdarker:resonarium_pike',
    'spartandeeperdarker:resonarium_lance',
    'spartandeeperdarker:resonarium_longbow',
    'spartandeeperdarker:resonarium_heavy_crossbow',
    'spartandeeperdarker:resonarium_throwing_knife',
    'spartandeeperdarker:resonarium_tomahawk',
    'spartandeeperdarker:resonarium_javelin',
    'spartandeeperdarker:resonarium_boomerang',
    'spartandeeperdarker:resonarium_battleaxe',
    'spartandeeperdarker:resonarium_flanged_mace',
    'spartandeeperdarker:resonarium_glaive',
    'spartandeeperdarker:resonarium_quarterstaff',
    'spartandeeperdarker:resonarium_scythe'])

  event.add('spartanweaponry:oilable_weapons', ['spartandeeperdarker:resonarium_dagger',
    'spartandeeperdarker:resonarium_parrying_dagger',
    'spartandeeperdarker:resonarium_longsword',
    'spartandeeperdarker:resonarium_katana',
    'spartandeeperdarker:resonarium_saber',
    'spartandeeperdarker:resonarium_rapier',
    'spartandeeperdarker:resonarium_greatsword',
    'spartandeeperdarker:resonarium_battle_hammer',
    'spartandeeperdarker:resonarium_warhammer',
    'spartandeeperdarker:resonarium_spear',
    'spartandeeperdarker:resonarium_halberd',
    'spartandeeperdarker:resonarium_pike',
    'spartandeeperdarker:resonarium_lance',
    'spartandeeperdarker:resonarium_longbow',
    'spartandeeperdarker:resonarium_heavy_crossbow',
    'spartandeeperdarker:resonarium_throwing_knife',
    'spartandeeperdarker:resonarium_tomahawk',
    'spartandeeperdarker:resonarium_javelin',
    'spartandeeperdarker:resonarium_boomerang',
    'spartandeeperdarker:resonarium_battleaxe',
    'spartandeeperdarker:resonarium_flanged_mace',
    'spartandeeperdarker:resonarium_glaive',
    'spartandeeperdarker:resonarium_quarterstaff',
    'spartandeeperdarker:resonarium_scythe'])
})



const fixer = [
  "dagger",
  "parrying_dagger",
  "longsword",
  "katana",
  "saber",
  "rapier",
  "greatsword",
  "battle_hammer",
  "warhammer",
  "spear",
  "halberd",
  "pike",
  "lance",
  "longbow",
  "heavy_crossbow",
  "throwing_knife",
  "tomahawk",
  "javelin",
  "boomerang",
  "battleaxe",
  "flanged_mace",
  "glaive",
  "quarterstaff",
  "scythe"
]


const fixer2 = [
  "dagger",
  "parrying_dagger",
  "longsword",
  "katana",
  "saber",
  "rapier",
  "greatsword",
  "battle_hammer",
  "warhammer",
  "spear",
  "halberd",
  "pike",
  "lance",
  "longbow",
  "heavy_crossbow",
  "tomahawk",
  "javelin",
  "boomerang",
  "battleaxe",
  "flanged_mace",
  "glaive",
  "scythe"
]

ServerEvents.tags('item', event => {

  for (let fixing of fixer) {
    event.add(`spartanweaponry:${fixing}s`, [`spartandeeperdarker:resonarium_${fixing}`])
    event.add(`spartanweaponry:${fixing}s`, [`spartandeeperdarker:warden_${fixing}`])
  }
  event.add("spartanweaponry:throwing_knives", ["spartandeeperdarker:resonarium_throwing_knife", "spartandeeperdarker:warden_throwing_knife"])
  event.add("spartanweaponry:quarterstaves", ["spartandeeperdarker:resonarium_quarterstaff", "spartandeeperdarker:warden_quarterstaff"])
})

ServerEvents.tags('item', event => {
  event.add('forge:weapons', ['spartandeeperdarker:warden_dagger',
    'spartandeeperdarker:warden_parrying_dagger',
    'spartandeeperdarker:warden_longsword',
    'spartandeeperdarker:warden_katana',
    'spartandeeperdarker:warden_saber',
    'spartandeeperdarker:warden_rapier',
    'spartandeeperdarker:warden_greatsword',
    'spartandeeperdarker:warden_battle_hammer',
    'spartandeeperdarker:warden_warhammer',
    'spartandeeperdarker:warden_spear',
    'spartandeeperdarker:warden_halberd',
    'spartandeeperdarker:warden_pike',
    'spartandeeperdarker:warden_lance',
    'spartandeeperdarker:warden_longbow',
    'spartandeeperdarker:warden_heavy_crossbow',
    'spartandeeperdarker:warden_throwing_knife',
    'spartandeeperdarker:warden_tomahawk',
    'spartandeeperdarker:warden_javelin',
    'spartandeeperdarker:warden_boomerang',
    'spartandeeperdarker:warden_battleaxe',
    'spartandeeperdarker:warden_flanged_mace',
    'spartandeeperdarker:warden_glaive',
    'spartandeeperdarker:warden_quarterstaff',
    'spartandeeperdarker:warden_scythe'])

  event.add('spartandeeperdarker:warden_weapons', ['spartandeeperdarker:warden_dagger',
    'spartandeeperdarker:warden_parrying_dagger',
    'spartandeeperdarker:warden_longsword',
    'spartandeeperdarker:warden_katana',
    'spartandeeperdarker:warden_saber',
    'spartandeeperdarker:warden_rapier',
    'spartandeeperdarker:warden_greatsword',
    'spartandeeperdarker:warden_battle_hammer',
    'spartandeeperdarker:warden_warhammer',
    'spartandeeperdarker:warden_spear',
    'spartandeeperdarker:warden_halberd',
    'spartandeeperdarker:warden_pike',
    'spartandeeperdarker:warden_lance',
    'spartandeeperdarker:warden_longbow',
    'spartandeeperdarker:warden_heavy_crossbow',
    'spartandeeperdarker:warden_throwing_knife',
    'spartandeeperdarker:warden_tomahawk',
    'spartandeeperdarker:warden_javelin',
    'spartandeeperdarker:warden_boomerang',
    'spartandeeperdarker:warden_battleaxe',
    'spartandeeperdarker:warden_flanged_mace',
    'spartandeeperdarker:warden_glaive',
    'spartandeeperdarker:warden_quarterstaff',
    'spartandeeperdarker:warden_scythe'])

  event.add('spartanweaponry:oilable_weapons', ['spartandeeperdarker:warden_dagger',
    'spartandeeperdarker:warden_parrying_dagger',
    'spartandeeperdarker:warden_longsword',
    'spartandeeperdarker:warden_katana',
    'spartandeeperdarker:warden_saber',
    'spartandeeperdarker:warden_rapier',
    'spartandeeperdarker:warden_greatsword',
    'spartandeeperdarker:warden_battle_hammer',
    'spartandeeperdarker:warden_warhammer',
    'spartandeeperdarker:warden_spear',
    'spartandeeperdarker:warden_halberd',
    'spartandeeperdarker:warden_pike',
    'spartandeeperdarker:warden_lance',
    'spartandeeperdarker:warden_longbow',
    'spartandeeperdarker:warden_heavy_crossbow',
    'spartandeeperdarker:warden_throwing_knife',
    'spartandeeperdarker:warden_tomahawk',
    'spartandeeperdarker:warden_javelin',
    'spartandeeperdarker:warden_boomerang',
    'spartandeeperdarker:warden_battleaxe',
    'spartandeeperdarker:warden_flanged_mace',
    'spartandeeperdarker:warden_glaive',
    'spartandeeperdarker:warden_quarterstaff',
    'spartandeeperdarker:warden_scythe'])
})


ServerEvents.tags('spartanweaponry:weapon_traits', event => {
  event.add('spartandeeperdarker:materials/warden', ['spartandeeperdarker:warden_dagger',
    'spartandeeperdarker:warden_parrying_dagger',
    'spartandeeperdarker:warden_longsword',
    'spartandeeperdarker:warden_katana',
    'spartandeeperdarker:warden_saber',
    'spartandeeperdarker:warden_rapier',
    'spartandeeperdarker:warden_greatsword',
    'spartandeeperdarker:warden_battle_hammer',
    'spartandeeperdarker:warden_warhammer',
    'spartandeeperdarker:warden_spear',
    'spartandeeperdarker:warden_halberd',
    'spartandeeperdarker:warden_pike',
    'spartandeeperdarker:warden_lance',
    'spartandeeperdarker:warden_longbow',
    'spartandeeperdarker:warden_heavy_crossbow',
    'spartandeeperdarker:warden_throwing_knife',
    'spartandeeperdarker:warden_tomahawk',
    'spartandeeperdarker:warden_javelin',
    'spartandeeperdarker:warden_boomerang',
    'spartandeeperdarker:warden_battleaxe',
    'spartandeeperdarker:warden_flanged_mace',
    'spartandeeperdarker:warden_glaive',
    'spartandeeperdarker:warden_quarterstaff',
    'spartandeeperdarker:warden_scythe'])
})


ServerEvents.tags('spartanweaponry:weapon_traits', event => {
  event.add('spartandeeperdarker:materials/resonarium', ['spartandeeperdarker:resonarium_dagger',
    'spartandeeperdarker:resonarium_parrying_dagger',
    'spartandeeperdarker:resonarium_longsword',
    'spartandeeperdarker:resonarium_katana',
    'spartandeeperdarker:resonarium_saber',
    'spartandeeperdarker:resonarium_rapier',
    'spartandeeperdarker:resonarium_greatsword',
    'spartandeeperdarker:resonarium_battle_hammer',
    'spartandeeperdarker:resonarium_warhammer',
    'spartandeeperdarker:resonarium_spear',
    'spartandeeperdarker:resonarium_halberd',
    'spartandeeperdarker:resonarium_pike',
    'spartandeeperdarker:resonarium_lance',
    'spartandeeperdarker:resonarium_longbow',
    'spartandeeperdarker:resonarium_heavy_crossbow',
    'spartandeeperdarker:resonarium_throwing_knife',
    'spartandeeperdarker:resonarium_tomahawk',
    'spartandeeperdarker:resonarium_javelin',
    'spartandeeperdarker:resonarium_boomerang',
    'spartandeeperdarker:resonarium_battleaxe',
    'spartandeeperdarker:resonarium_flanged_mace',
    'spartandeeperdarker:resonarium_glaive',
    'spartandeeperdarker:resonarium_quarterstaff',
    'spartandeeperdarker:resonarium_scythe'])
})

