#KubeJS Common Properties
#Mon Feb 17 15:04:49 WIB 2025
matchJsonRecipes=true
allowAsyncStreams=true
announceReload=true
serverOnly=false
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=minecraft\:purple_dye
startupErrorGUI=true
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=
AdvJSExample=true
startupErrorReportUrl=
AdvJSDebug=true
