#Darkness properties file
#Thu Apr 16 23:20:39 WIB 2026
dark_nether_fog=0.5
invert_biome_darkness=false
only_affect_block_light=false
dark_end_fog=0.0
dark_overworld=true
gradual_moon_phase_darkness=false
dark_default=true
dark_end=true
dark_skyless=true
dark_nether=true
ignore_moon_phase=false
